Neos:
  Neos:
    Ui:
      resources:
        javascript:
          PunktDe.NeosEnvironmentDisplay:Display:
            resource: 'resource://PunktDe.NeosEnvironmentDisplay/Public/NeosEnvironmentDisplay/Plugin.js'
        stylesheets:
          PunktDe.NeosEnvironmentDisplay:Display:
            resource: 'resource://PunktDe.NeosEnvironmentDisplay/Public/NeosEnvironmentDisplay/Plugin.css'

      frontendConfiguration:
        'PunktDe.NeosEnvironmentDisplay':
          backgroundColor: ''
          label: ''
          secondaryLabel: ''
          icon: ''
